# -*- coding: utf-8 -*-
"""rt-lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wNyU5R9CVmyccjA_1LWHYLmBGrx7WnKL

1. Загружаете любую картинку из интернета.
2. Приводите ее в соответствующий формат (черно-белая, нормализованная, см. справки по Radon Transform в Matlab и Python). Это будет оригинальное изображение.  
3. Выполняете над полученной матрицей преобразование Радона в трех вариантах сканирования (скажем, поворот на 1, 5 и 10 градусов).
4. Для всех вариантов выполняете обратное преобразование Радона (Inverse Radon Transform).
5. Сравниваем оригинал и полученные реконструкции.
6. Кроме того, нужно рассказать теорию (что такое преобразование Радона, как получить формулу обращения, используя преобразование Фурье).
"""


import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.color import rgb2gray
from skimage import img_as_float
from skimage.transform import radon, iradon

image_orig = imread("img.jpg")

image_gray = rgb2gray(image_orig)

image_norm = img_as_float(image_gray)

angles = [1, 5, 14]

radon_results = {}
reconstructions = {}

for angle in angles:
  theta = np.arange(0, 180, angle)

  radon_results[angle] = radon(image_norm, theta=theta, circle=True)

  reconstructions[angle] = iradon(radon_results[angle], theta=theta, circle=True)

fig, axes = plt.subplots(len(angles), 3, figsize=(10, 10))

for i, angle in enumerate(angles):
  axes[i,0].imshow(image_norm, cmap="gray")
  axes[i,0].set_title("Оригинал ч/б")
  axes[i,0].axis("off")

  axes[i,1].imshow(radon_results[angle], cmap="gray", aspect="auto")
  axes[i,1].set_title(f"Radon {angle}°")
  axes[i,1].axis("off")

  axes[i,2].imshow(reconstructions[angle], cmap="gray")
  axes[i,2].set_title(f"IRadon {angle}°")
  axes[i,2].axis("off")

plt.tight_layout()
plt.show()